update public.jobs
set
  status = 'Closed',
  updated_at = now()
where source_type = 'federated'
  and status = 'Open'
  and (
    coalesce(application_url, source_url) is null
    or source_job_id is null
    or title ilike '%view similar jobs%'
    or description ilike '%view similar jobs with this employer%'
  );

create temporary table tmp_curated_jobs on commit drop as
select *
from (
  values
      (
        'cfad-graphic-design-intern',
        'Graphic Design Intern',
        'North Canvas Studio',
        'Internship',
        'Quezon City',
        'Hybrid',
        'Support campaign visuals, social content, and layout refinements for student and youth-facing brand work.',
        array['Prepare social graphics and simple print-ready layouts','Adapt brand assets into campaign variations','Organize working files and design handoff notes']::text[],
        array['Graphic Design','Adobe Photoshop','Adobe Illustrator','Layout Design','Branding']::text[],
        array['Photography','Adobe InDesign']::text[],
        array['Mentorship','Portfolio reviews','Flexible schedule']::text[],
        now() - interval '1 day'
      ),
      (
        'cfad-ui-ux-design-intern',
        'UI/UX Design Intern',
        'Pixel Foundry Labs',
        'Internship',
        'Makati City',
        'Hybrid',
        'Help map student user flows, build wireframes, and polish interface mockups for education and career tools.',
        array['Draft wireframes for mobile and web screens','Assist with design QA before handoff','Summarize user feedback into actionable design notes']::text[],
        array['UI/UX','Figma','Wireframing','Design Systems','Communication']::text[],
        array['Prototype Testing','Graphic Design']::text[],
        array['Mentorship','Learning budget','Hybrid setup']::text[],
        now() - interval '2 days'
      ),
      (
        'cfad-multimedia-artist-intern',
        'Multimedia Artist Intern',
        'Studio Luntian Media',
        'Internship',
        'Pasig City',
        'On-site',
        'Create visual assets across digital campaigns, reels, and event content for youth-oriented brands.',
        array['Produce image assets for web and social posts','Assist with short-form video edits','Prepare export-ready files for marketing use']::text[],
        array['Multimedia','Adobe Photoshop','Video Editing','Branding','Creative Collaboration']::text[],
        array['After Effects','Photography']::text[],
        array['Production exposure','Creative reviews','Transportation allowance']::text[],
        now() - interval '3 days'
      ),
      (
        'cfad-illustration-assistant',
        'Illustration Assistant',
        'Haraya Publishing House',
        'Job',
        'Manila City',
        'Hybrid',
        'Support editorial and promotional illustration work for educational, cultural, and community publications.',
        array['Refine illustration assets based on art direction','Prepare layered source files for publishing','Coordinate revisions across the content team']::text[],
        array['Illustration','Adobe Illustrator','Digital Illustration','Color Theory','Documentation']::text[],
        array['Layout Design','Typography']::text[],
        array['Mentorship','Project ownership','Hybrid setup']::text[],
        now() - interval '4 days'
      ),
      (
        'cfad-exhibit-design-assistant',
        'Exhibit Design Assistant',
        'Museo Habagat',
        'Job',
        'Manila City',
        'On-site',
        'Assist with exhibit layouts, visitor signage, and installation planning for public-facing cultural programs.',
        array['Help develop exhibit graphics and wayfinding elements','Coordinate production requirements for installations','Document revisions with curatorial and fabrication teams']::text[],
        array['Exhibit Design','Layout Design','Graphic Design','Documentation','Teamwork']::text[],
        array['Illustration','Photography']::text[],
        array['Museum access','Project exposure','Team workshops']::text[],
        now() - interval '5 days'
      ),
      (
        'cfad-photography-content-intern',
        'Photography and Content Intern',
        'Kislap Creative Collective',
        'Internship',
        'Taguig City',
        'Hybrid',
        'Capture product and event visuals, assist with edits, and prepare content assets for campaign publishing.',
        array['Assist on photo shoots and content days','Select and lightly retouch approved images','Organize media libraries for campaign use']::text[],
        array['Photography','Content Creation','Adobe Photoshop','Documentation','Communication']::text[],
        array['Video Editing','Social Media']::text[],
        array['Creative mentorship','Portfolio shoots','Flexible hours']::text[],
        now() - interval '6 days'
      ),
      (
        'frontend-developer-trainee',
        'Frontend Developer Trainee',
        'Launchpad Digital',
        'Job',
        'Cebu City',
        'Hybrid',
        'Build responsive interfaces and support frontend feature delivery for internal products and partner websites.',
        array['Translate mockups into responsive screens','Fix UI bugs and polish reusable components','Write clear handoff and testing notes']::text[],
        array['React','JavaScript','HTML','CSS','Git']::text[],
        array['TypeScript','Figma']::text[],
        array['HMO','Hybrid setup','Mentor pairing']::text[],
        now() - interval '2 days'
      ),
      (
        'full-stack-junior-engineer',
        'Junior Full Stack Engineer',
        'Orbit Campus Systems',
        'Job',
        'Quezon City',
        'Hybrid',
        'Support product teams by building small backend and frontend features for campus and workforce tools.',
        array['Implement small product features across the stack','Debug reported issues with senior guidance','Write concise technical notes and test steps']::text[],
        array['JavaScript','React','Node.js','SQL','Git']::text[],
        array['TypeScript','Testing']::text[],
        array['Laptop support','Training budget','Growth path']::text[],
        now() - interval '3 days'
      ),
      (
        'embedded-systems-trainee',
        'Embedded Systems Trainee',
        'Ampere Robotics',
        'Internship',
        'Laguna',
        'On-site',
        'Assist with firmware validation, hardware bring-up, and documentation for device prototypes.',
        array['Run hardware and firmware test checklists','Log defects and reproduction steps','Prepare documentation for sensors and control boards']::text[],
        array['Embedded','Firmware','Microcontroller','Documentation','Problem Solving']::text[],
        array['Arduino','C++']::text[],
        array['Lab access','Mentorship','Hands-on prototypes']::text[],
        now() - interval '4 days'
      ),
      (
        'iot-project-assistant',
        'IoT Project Assistant',
        'SignalNest Technologies',
        'Internship',
        'Pasig City',
        'Hybrid',
        'Support proof-of-concept IoT builds, dashboards, and deployment checklists for pilot clients.',
        array['Assist with IoT device setup and validation','Prepare simple status dashboards and logs','Document installation findings for the project team']::text[],
        array['IoT','Python','Documentation','Analytics','Communication']::text[],
        array['Raspberry Pi','SQL']::text[],
        array['Mentorship','Pilot project exposure','Hybrid setup']::text[],
        now() - interval '5 days'
      ),
      (
        'data-analyst-associate',
        'Data Analyst Associate',
        'Crestview Insights',
        'Job',
        'Mandaluyong City',
        'Hybrid',
        'Prepare dashboards, clean reports, and support recurring business analysis for operations and growth teams.',
        array['Prepare recurring dashboards and weekly reports','Validate source data before publishing insights','Present trends in simple business language']::text[],
        array['Analytics','SQL','Excel','Reporting','Communication']::text[],
        array['Power BI','Python']::text[],
        array['HMO','Hybrid setup','Career coaching']::text[],
        now() - interval '2 days'
      ),
      (
        'business-analyst-trainee',
        'Business Analyst Trainee',
        'ProcessSpring Solutions',
        'Job',
        'Makati City',
        'Hybrid',
        'Work with operations and product teams to map workflows, gather requirements, and track process improvements.',
        array['Capture current-state workflows and pain points','Document meeting notes and requirement updates','Support testing and rollout coordination']::text[],
        array['Business Analysis','Documentation','Analytics','Communication','Process Improvement']::text[],
        array['SQL','Excel']::text[],
        array['Mentorship','Hybrid setup','Certification support']::text[],
        now() - interval '3 days'
      ),
      (
        'qa-engineer-junior',
        'Junior QA Engineer',
        'Harbor Software Co.',
        'Job',
        'Pasig City',
        'Hybrid',
        'Help maintain release quality by executing test cases, logging defects, and validating fixes across web features.',
        array['Execute regression and smoke test plans','Log and retest defects with clear evidence','Help maintain test case documentation']::text[],
        array['QA','Testing','Bug Tracking','Documentation','Quality Assurance']::text[],
        array['Test Planning','Cypress']::text[],
        array['HMO','Mentorship','Hybrid work']::text[],
        now() - interval '4 days'
      ),
      (
        'technical-support-associate',
        'Technical Support Associate',
        'NorthGrid Cloud',
        'Job',
        'Taguig City',
        'On-site',
        'Provide first-line support for SaaS users, troubleshoot issues, and keep customer-facing documentation current.',
        array['Triage incoming technical issues and update tickets','Reproduce product problems before escalation','Refresh support guides for common cases']::text[],
        array['Technical Support','Troubleshooting','Customer Service','Documentation','Communication']::text[],
        array['Networking','SaaS']::text[],
        array['Shift support','Training tracks','Team incentives']::text[],
        now() - interval '2 days'
      ),
      (
        'marketing-content-assistant',
        'Marketing Content Assistant',
        'Brightlane Growth Studio',
        'Job',
        'Quezon City',
        'Hybrid',
        'Support campaign planning, content calendars, and performance reporting for digital acquisition work.',
        array['Draft content support materials and captions','Coordinate campaign assets with design teammates','Track simple engagement metrics and reporting']::text[],
        array['Marketing','Copywriting','Social Media','Communication','Research']::text[],
        array['Graphic Design','Analytics']::text[],
        array['Hybrid setup','Mentorship','Learning sessions']::text[],
        now() - interval '3 days'
      ),
      (
        'hr-operations-assistant',
        'HR Operations Assistant',
        'PeopleFirst Services',
        'Job',
        'Makati City',
        'On-site',
        'Support hiring coordination, onboarding tasks, and employee record upkeep for a growing support team.',
        array['Coordinate interviews and onboarding checklists','Maintain organized employee records and trackers','Help draft internal people operations updates']::text[],
        array['HR','Recruitment','Onboarding','Documentation','Communication']::text[],
        array['Excel','Employee Relations']::text[],
        array['HMO','On-site coaching','Clear growth path']::text[],
        now() - interval '4 days'
      ),
      (
        'finance-operations-associate',
        'Finance Operations Associate',
        'Summit Ledger Partners',
        'Job',
        'Pasay City',
        'Hybrid',
        'Handle reconciliations, reporting support, and payment tracking for finance operations workflows.',
        array['Prepare reconciliations and transaction trackers','Assist with monthly reporting packs','Coordinate follow-ups on payment and invoice issues']::text[],
        array['Accounting','Excel','Reconciliation','Documentation','Problem Solving']::text[],
        array['Bookkeeping','Financial Reporting']::text[],
        array['Hybrid work','HMO','Upskilling support']::text[],
        now() - interval '5 days'
      ),
      (
        'admin-project-coordinator',
        'Admin Project Coordinator',
        'Vertex Service Hub',
        'Job',
        'Muntinlupa City',
        'On-site',
        'Keep project records organized, coordinate schedules, and support day-to-day administrative operations.',
        array['Maintain trackers and project filing systems','Coordinate schedules, meetings, and follow-ups','Prepare clear status updates for stakeholders']::text[],
        array['Administration','Scheduling','Documentation','Communication','Data Entry']::text[],
        array['Excel','Customer Service']::text[],
        array['Team support','Stable schedule','On-site coaching']::text[],
        now() - interval '6 days'
      )
 ) as t(
  source_job_id,
  title,
  company_name,
  category,
  location,
  work_type,
  description,
  responsibilities,
  required_skills,
  nice_to_have_skills,
  benefits,
  posted_at
);

insert into public.jobs (
  title,
  company_name,
  category,
  location,
  work_type,
  salary_min,
  salary_max,
  salary_currency,
  salary_interval,
  description,
  responsibilities,
  required_skills,
  nice_to_have_skills,
  benefits,
  application_url,
  status,
  review_status,
  source_platform,
  source_type,
  source_url,
  source_job_id,
  normalized_hash,
  raw_payload,
  posted_at,
  scraped_at,
  expires_at,
  updated_at
)
select
  title,
  company_name,
  category,
  location,
  work_type,
  null,
  null,
  'PHP',
  'monthly',
  description,
  responsibilities,
  required_skills,
  nice_to_have_skills,
  benefits,
  null,
  'Open',
  'Approved',
  'SkillBridge Curated',
  'manual',
  null,
  source_job_id,
  md5(lower(source_job_id || '|' || title || '|' || company_name)),
  jsonb_build_object('seed', 'curated-refresh', 'job_family', category),
  posted_at,
  posted_at,
  now() + interval '60 days',
  now()
from tmp_curated_jobs
on conflict (source_platform, source_job_id) do update
set
  title = excluded.title,
  company_name = excluded.company_name,
  category = excluded.category,
  location = excluded.location,
  work_type = excluded.work_type,
  description = excluded.description,
  responsibilities = excluded.responsibilities,
  required_skills = excluded.required_skills,
  nice_to_have_skills = excluded.nice_to_have_skills,
  benefits = excluded.benefits,
  status = 'Open',
  review_status = 'Approved',
  source_type = 'manual',
  normalized_hash = excluded.normalized_hash,
  raw_payload = excluded.raw_payload,
  posted_at = excluded.posted_at,
  scraped_at = excluded.scraped_at,
  expires_at = excluded.expires_at,
  updated_at = now();
